---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "apps.cloudcasa.io/v1alpha1",
          "kind": "Cloudcasa",
          "metadata": {
            "name": "cloudcasa-sample"
          },
          "spec": {
            "clusterID": "",
            "image": {
              "repository": "cloudcasaAgent.azurecr.io/catalogicsoftware/amds-kagent",
              "tag": "3.1.0-prod"
            },
            "imagePullSecret": null,
            "server": {
              "address": "agent.cloudcasa.io:443",
              "skipTLSVerification": false
            }
          }
        }
      ]
    capabilities: Basic Install
    categories: Storage
    containerImage: registry.connect.redhat.com/catalogicsoftware/cloudcasa-operator@sha256:3afcad05640cc9d23cab32dcdde65259859b26db71b773de90708707dd4d301c
    createdAt: "2026-02-23T00:00:00Z"
    description: CloudCasa is a powerful and easy-to-use data protection service for Kubernetes and cloud databases.
    features.operators.openshift.io/disconnected: "false"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/proxy-aware: "true"
    features.operators.openshift.io/tls-profiles: "true"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operators.operatorframework.io/builder: operator-sdk-v1.8.0-ocp
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: cloudcasa-operator.v4.0.0
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Cloudcasa
      name: cloudcasas.apps.cloudcasa.io
      version: v1alpha1
      description: Agent for backup and restore services.
      displayName: Cloudcasa
      specDescriptors:
      - description: Cluster ID for registering the User Kubernetes to Cloudcasa
        displayName: Cluster ID
        path: cluster_id
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:password
      resources:
      - kind: Deployment
        version: apps/v1
        name: ""
      - kind: Pod
        version: v1
        name: ""
      - kind: Service
        version: v1
        name: ""
  description: CloudCasa backup and migration service agent for Kubernetes
  displayName: cloudcasa-operator
  icon:
  - base64data: |
      /9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxANEBASDw4QFRASFRAWEBIVFRUPEBgQFREWFx
      YSGBUYHCghGBolHRUXIT0hJykrLi4uFx8zRDM4QyktLi4BCgoKDg0OGRAQGysfICUtLS0xLSst
      NzEuKy4rLSstKy4tLS0uLjcrLTUuKy03Ky0yKy0tLS01LS0rLSstLS0tK//AABEIAMgAyAMBIg
      ACEQEDEQH/xAAcAAEAAgMBAQEAAAAAAAAAAAAABQcBBAYDCAL/xABDEAABAwICBQgGCAQGAwAA
      AAABAAIDBBEFIQYxQVFhBxITIjJxgZEjQlKhwdEUM2JygpKisXOywvEWJDRTs/BDY+H/xAAaAQ
      EAAgMBAAAAAAAAAAAAAAAAAwQBAgUG/8QALREAAgIBBAAEBQMFAAAAAAAAAAECAxEEEiExBRNB
      USJhcaGxFIGRIzJC0eH/2gAMAwEAAhEDEQA/ALxREQBERAEREAREQBERAEREAREQBERAEREARE
      QBERAEREAREQBERAEREAREQBERAYReFXVRwtL5Xtawa3ONguEx3lHa27aOPnH/HHghvg3WfG3c
      toxb6JqdPZa8QRYDnAZkqHrtKqGDJ9VHcbG3kPd1b2VPYnjdTVn0873D2b81ng0ZKPUyp9zrVe
      ELuyX8FsVHKRRt7Mc7uIa1o97r+5ab+U2PZSvPe4D4FVoi38mJcj4Vp12m/3LOj5TIfWppRvsW
      nP3KQpeUGhf2jLH95l/5CVUSI6YmZeEad9ZX7/7L6oMZpqn6meNx3Bw535da3187g21KfwnTCs
      pbASmRg9STri3B2seajdHsU7vBJLmuWfky6UXKYBpxTVdmyehlOxx6hPB/wA7LqwVC4tdnHtpn
      VLbNYMoiLBEEREAREQBERAEREAREQBc/pRpTDhzbHrzEdSIHP7zj6rVq6a6VNw9nMjsah46o1h
      rfbcPhtVQVNQ+Z7pJHFz3G7nHMkqWuvPLOjo9F5nxT6/Ju43jlRXv5077j1WDJje5vx1qOWF70
      lLJO8MiY573amtFyrKwkd6KjXHC4R5LLWkkAAknUBmVYeA8m97OrZLaj0TD7nP+Xmu3oMIpaMe
      hhjZYZut1rcXHM+JUcrUuilb4pXDiHxP7FOUejFdN2KSW29w6Meb7KRj0BxAjONg4F4+F1Y1Zp
      ZQQZOqWE7mXk/lBUXLyi0Tb2bO7uaB+7gtd830iFa3WT5hD7HGyaBYg0ZRMdwD2/GyjazRutg+
      spZbbSB0g823CsOLlGona2zt72tP7OKlKPS6gnybUsB3PvF/MAs75rtG367WQ5lXx9GUoRZFem
      IYNSVo9LFG+4yeMnW4PGfvXEY7ydOZd9G8vGvo32Dvwu1Hxt3raNqffBb0/i1U3tn8L+xwS6nR
      jTOaisyS8kHsk9do+yTs4HLuXMzwvicWSNc1wyc0ixB7l+FI0pLk6NtVd8MTWUX7h2IRVUbZIX
      hzDtGw7iNh4LbVMaG4hV083+WifI11ukjAJaRvvqaeKuSJxIBLSCQLg2uDuNsvJU7IbWeS12k/
      T2bU8r0/6eiIi0KQREQBERAEREAUNpPjjMPp3SOzecome0/Z4DWpdxtmqR01x019S4tPoY7thG
      y183+Jz7rLeuO5lnS0ebPnoh62rkqJHySuLnvJLid/y4LxWFIYDhElfOyGPWc3O2NYNbj/3XYK
      1wkeg3RhHPSR76OYBNiMnMjFmC3SSHstHxO4K4MBwGnw+PmxNF7deQ5vd3ndw1LYwbC4qKFsUL
      bNGs+s521xO0lV9yk49U9KaYNdHDbXfOUb7j1dlvPcIHJzeEcids9XZsi8ImNJOUGKC7KUCWQa
      3n6oHw7fhlxVe4rjlTWG88znDY3ssHc0ZKNWQFNGCidbT6SqlcLn3Cyp/DNDa6psRDzGnU6Q9H
      +nte5T8HJjKR6SrY0/ZYX/uQsuyKJZa6iDw5I4JF303JjIB1KtjjxjLP2cVB4loVXU4J6ISNGs
      xnn/pyd7kVkWSV6/Tz4UkRmGYzUUhvBM5v2b3Ye9pyKsDR3lBjlIZVtEbjqkH1RPH2feFWLmkE
      gggjWDkbokoRkbX6KnUL4lz7ou3HtHqfEWdcAPt1JW9obs9o4f3UThPJ9Sw2MxdM7j1I/yj4kr
      ktENLn0TmxykupidWtzPtN4cPLjbNPO2VrXscHNcAWuGYIO1V5b4cZPP6mOp0n9Pc9r6aFPTMi
      aGxsa1o1NaA1o8AvVFlRHMbbCIiAIiIAiIgCIiA5TlGxf6LRua02knvG3fzLdd3ll+IKml1/Kh
      iHTVvRg9WBobbZz3dZx8i0fhXHq1WsI7mjr2V/NmVdGgeAChpw57fTSgOkvrA9VnC37kqudAsK
      +l1sYcLxx+kfuIaRzR4uI8AVdq0tl6FfxC7qtfuFF6QYHFiERjlGeZY8dprt4+W1SiKDo5kZOL
      yik/8HVn0o03R5jPpM+i6O/b53w1qzNHNEqagAIbz5rZyuGd/sj1R3Z8SugRbysbLV2tstSi+P
      p6mURFoVAiIgILSDRinrweezmyW6srcnjv9ocCqn0gwKbD5OZKLtN+jkHZcPgeH91ei0MZwqOt
      idFKLg6jta7Y4cVLXY49nR0XiE6JJN5j+PoUMu25O9JDBIKaV3opD6Mn1ZD6vcf37yuVxfDX0c
      z4ZB1mHXsLdjhwIWo0271ZaUkemuqhqacPlPpn0OsqB0Nxf6bSse4+kb1JPvtGvxFj4qdVJrDw
      eLsrdc3GXaMoiLBoEREAREQBYKytPF5ejgmd7Mch8mEoZXLKFxeq6eonlv25JHDuLjb3LUWFlX
      EegjwsFp8ktFzYJpiM5Hho+6wfNx8l3y57QKHo8Ophva5353ud8V0CqzeWziXy3WSfzMoiLUhC
      IiAIiIAiIgCIiA4TlRwkPhbUtHWiIa8743HLycf1FVgr7xylE9NPGR22PA7+bkfOyoRWqXlYPT
      eD3OVTg/R/k7jksr+ZUSQk5SM5w++w/Jx8laKo/Q+o6Kupnb5A38/U/qV4BR3L4jneMQUb9y9U
      ZREUJygiIgCIiAKL0o/0NZ/AqP+JylFp4tF0lPOz2o5G+bCEXZmPaPnlFhZVw7yZfWiP+hpP4M
      X8oUwue0Cn6TDqY7mub+V7m/BdCqku2cOz+9/UIiLBoEREAREQBERAEREBh2or52da5te2y+uy
      vvHKsQU08hPYjeR3802HnZUGrFHqd3wZY3v6Ejo9/rKX+PB/yNV8hUdodB0tfSttqkDvydf8Ap
      V4rF/ZF4y82x+hlERQHHCIiAIiIAhREB874vS/R6ieL/bkkaO4OIB8lqLsOVHDuhrekA6s7A7h
      z29Vw9zT+JcercXlHaqnuimWpySVwfTzQk5xvDh914+bT5rvlSGgOLfQ62MuNo5fRv3AOPVd4O
      A8Lq71XsWGc7VQ22Z9zKIi0KwREQBERAEREBhEWhjWKx0ULpZTZrdQ2udsaN5KYMxTk8I5PlSx
      cRwspmnrSkOeN0bTl5uH6SqvW3jGJSVkz5pD1nnVsDdjRwAWoBfIK5CO1HqdHUqalH+TuOSvD+
      fUSTEZRM5o++/8A+A+atNQWhmD/AEGkjY4ekd15fvu2eAsPBTyrWSzI8/rbvNucl10ERFoVQiI
      gCIiAIiIDk+UjB/pVG57ReSA9I3eW267fLP8ACFS6+knC+tUbptgJw+qc1o9DJd0J2c3azwOXd
      bepqpehe0ln+LIBXXoDj4rqYB7vTxWbJvI9WTxHvBVJqSwDGJKCdk0WsZObscw62n/uuxUk47k
      WL6vMj8z6BUVpDjkOHwmSU56mMHac7cPnsXtg2KxVsLZYXXa7WPWa7a1w2EKvOUzAKoymqDnSw
      2tbbEN1h6vHz3mvGPOGc6uCc9suCB/xpWfSjUiTM5dFri6O/Y5vx1qz9G9LqbEAA13Mm2xOI51
      /sn1h3Z8AqNX6BtmNancEzoT08Jrjg+kQipDC9Nq+mAAm6Ro9WUdJ+rte9dBBypSgekpGO3815
      Z+4KidUipLR2Lrks9FWM/KlIR1KNjT9qQv/AGaFBYnpxX1AI6URtOyIcz9WbveiqkzaGitk+eC
      z9IdKKbD2npH86X1Ym5vPf7I4lVHpDj82Iyc+U2aL9HGOy0cN53n+yiXOLiSSSTmSczdFNCCid
      TTaWFXPb9zK7jk40aM8gqZm+ijPogfWkHrdw/fuK0tDtDpK5wlmBbTA69Tn/Zbw3u8uFu08DYm
      tYxoaxoAa0ZAAbFrZZ6Ii1utUU64Pn1PZERVziBERAEREAREQBERAYUNpVgTMRp3RusHjOJ/sv
      2eB1FTKyieDKbTyj5yraSSnkfFK0tewkOB3/LivBXRpvok3EWc+Ozalg6p1B7fYcf2OxU5U074
      XuZIwte02c0ixBVmEsnUpuU18yT0b0hmw6XnxG7XW6SMnquHwO4q5MAx+nxGPnRPHO9eN3bb3j
      aOOpUGvejq5IHh8T3Me3U5psUlDItoVnK4Zaek3J5DUF0lIRFIcyz/wuPhmzwy4KuMWwGqojae
      BzR7XajPc4ZLtsA5S7WZWx32dLGPe5ny8l3WH4vS1rfQzRyAjNt+tbiw5jxC03Sj2V1ZbVxJZR
      8+rKvWu0RoKjN9LGDvZeI9/UIuoiXk1oXanTt7nj+ppWytRNHWw9clQrKt2Lk1oW63Tu73t/pa
      FK0eh2HwZtpWE733l9ziQnmo3eugukyncKwWprDaCB7thdazB3uOQViaOcnccJD6xwkeMxGPqg
      eO1/uHeupxHGaWib6aaNlhk2/WtwYM/cuGx7lIc67KJhb/7X2Lvws1DvPksbpS6NPOvv4gsI7L
      SDSGnw2Mc8jn29HE23OO7LYOKh8I5RKSewmDoXcevH+YfEBVPUVD5XOfI9znuzc5xuSe9ea2VS
      LEPDq9uJPn3PomnqGStDo3tc06nNIc0+IXqqT0Lw+sqJv8AKyviaCOllBIaBuI1OO4K6Y2kAAu
      LiALk2uTvNsvJQzjtfZzNTQqZYUsnoiItCuEREAREQBERAEREAXOaVaJw4k256k4HUlAz+64es
      33jYujWETwZjJxeUfP2OYFUUD+ZPGQPVeM43DeHfDWo1fRlZRxzsLJY2vY7W1wuFX+PcmYJL6K
      Tm7eikuW9zX6x4371PGxepfq1SfEitFlriCCCQRqIyK38UwSpoz6eB7B7Vrs8HDI+aj1KnkuRk
      pLgmaPSmvg7FXLYag49KPJ91Js5QsQAzkjPExtv7rLk1lY2r2HlQfaR1UnKDiLhlKxvERt+N1G
      1mk9dP26uWx1hp6MeTbKHWUUUbxqrXSRkm/ftRALroMI0NrauxEJjZ7ct4x4DWfALOUiR2Rgst
      4OfXV6LaFT13NfIDHT5dYjruH2R8Tl3rt9H9A6Wks+QdNKM7vHUB4M+d/BdaAopW+xQv8Q4xX/
      JqYZh0VJG2KFgaxuwayd5O08VtoigOY228syiIhgIiIAiIgCIiAIiIAiIgCIiA/LmgixAI3HMK
      Er9EaCozfSxg72XiP6bXU4iZaMqTXTOIqOTOjd2JZ2cOc1w97b+9abuSyO+VY8DiwH4qw1lbb5
      e5KtRYvUr6LkuhHaqpT3Na397qQpOTmgj7Qlk+8+w/QAuwWU3yD1Fj9SOw/BKWl+pp42H2g0c7
      8xzPmpBEWuSJtvsyiIhgIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIi
      AIiID/9k=
    mediatype: image/jpeg
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - apps.cloudcasa.io
          resources:
          - cloudcasas
          - cloudcasas/status
          - cloudcasas/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: cloudcasa-operator-controller-manager
      deployments:
      - name: cloudcasa-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:648b14e4158da2a85eedb46b3456fb502d680d52d375ad34bf45b4b94f8b2ef6
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                - --leader-election-id=cloudcasa-operator-v4
                image: registry.connect.redhat.com/catalogicsoftware/cloudcasa-operator@sha256:3afcad05640cc9d23cab32dcdde65259859b26db71b773de90708707dd4d301c
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 100m
                    memory: 90Mi
                  requests:
                    cpu: 100m
                    memory: 60Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: cloudcasa-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: cloudcasa-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - backup
  - storage
  - cloudcasa
  links:
  - name: Cloudcasa Operator
    url: https://cloudcasa.io
  minKubeVersion: 1.24.0
  maintainers:
  - email: support@cloudcasa.io
    name: CatalogicSoftware
  maturity: alpha
  provider:
    name: Catalogic Software
    url: https://cloudcasa.io
  relatedImages:
  - image: registry.connect.redhat.com/catalogicsoftware/cloudcasa-operator@sha256:3afcad05640cc9d23cab32dcdde65259859b26db71b773de90708707dd4d301c
    name: manager
  - image: registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:648b14e4158da2a85eedb46b3456fb502d680d52d375ad34bf45b4b94f8b2ef6
    name: kube-rbac-proxy
  version: 4.0.0
